package com.king.chat.socket.bean;

import java.io.Serializable;

public class MediaSrc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediasrc.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediasrc.medianame
     *
     * @mbg.generated
     */
    private String medianame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediasrc.mediapath
     *
     * @mbg.generated
     */
    private String mediapath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediasrc.mediatype
     *
     * @mbg.generated
     */
    private String mediatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mediasrc
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediasrc.id
     *
     * @return the value of mediasrc.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediasrc.id
     *
     * @param id the value for mediasrc.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediasrc.medianame
     *
     * @return the value of mediasrc.medianame
     *
     * @mbg.generated
     */
    public String getMedianame() {
        return medianame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediasrc.medianame
     *
     * @param medianame the value for mediasrc.medianame
     *
     * @mbg.generated
     */
    public void setMedianame(String medianame) {
        this.medianame = medianame == null ? null : medianame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediasrc.mediapath
     *
     * @return the value of mediasrc.mediapath
     *
     * @mbg.generated
     */
    public String getMediapath() {
        return mediapath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediasrc.mediapath
     *
     * @param mediapath the value for mediasrc.mediapath
     *
     * @mbg.generated
     */
    public void setMediapath(String mediapath) {
        this.mediapath = mediapath == null ? null : mediapath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediasrc.mediatype
     *
     * @return the value of mediasrc.mediatype
     *
     * @mbg.generated
     */
    public String getMediatype() {
        return mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediasrc.mediatype
     *
     * @param mediatype the value for mediasrc.mediatype
     *
     * @mbg.generated
     */
    public void setMediatype(String mediatype) {
        this.mediatype = mediatype == null ? null : mediatype.trim();
    }
}